---
- hosts: [SAM-MBP]
  remote_user: sboynton
  become: yes
  tasks:
      - name: Unmount Callisto
        shell: "sudo diskutil unmount force /Volumes/Callisto"

      - name: Unmount Europa
        shell: "sudo diskutil unmount force /Volumes/Europa"

      - name: Unmount Ganymede
        shell: "sudo diskutil unmount force /Volumes/Ganymede"

      - name: Remove directories
        file:
            path: /Volumes/{{ item }}
            state: absent
        with_items:
            - Callisto
            - Europa
            - Ganymede

      - name: Clear Callisto from /etc/fstab
        lineinfile:
            dest: /etc/fstab
            state: absent
            regexp: "callisto"

      - name: Clear Europa from /etc/fstab
        lineinfile:
            dest: /etc/fstab
            state: absent
            regexp: "europa"

      - name: Clear Ganymede from /etc/fstab
        lineinfile:
            dest: /etc/fstab
            state: absent
            regexp: "ganymede"

